### PR TITLE
Adding a security category and securitynewsletter.co

### PR DESCRIPTION
**Pull request by dietervds**
Hey @webpro!

First of all: thanks for a great list. I picked up a few I didn't know about yet.

Second: I made a PR adding my own securitynewsletter.co to the list, in a new "Security" category, in case you'd find it worthy to add to the list.

Cheers!

### CODE REVIEW

**Comment by webpro** [comment]
Thanks @dietervds! Could you please add it to the general section at the top? Happy to merge it then.

**Comment by dietervds** [comment]
Sure thing, done! Thanks!

**Comment by webpro** [comment]
Sorry to bother you again, but the list is ordered by date of the first issue... :)

**Comment by dietervds** [comment]
Woops, sorry about that. Should be fixed now :-)

**Comment by webpro** [comment]
Thanks!

**Pull request merged**
