### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Kvaibhav01**
Added Dev Updates

### CODE REVIEW

**Comment by webpro** [comment]
Thanks @Kvaibhav01! Please update the date format and I'm happy to merge this. I think there's also an RSS feed, right?

**Comment by Kvaibhav01** [comment]
I've updated the date format and there's no RSS feed as of now. Thanks!

**Comment by webpro** [comment]
Please only provide one Twitter handle if they're identical.

I think this is the RSS feed (it's in the upper right of a newsletter page): https://us3.campaign-archive.com/feed?u=34a5509fd3336ce51db8f28d6&id=78abab66ab

**Comment by Kvaibhav01** [comment]
I've added my about.me website link and I don't know about the RSS feed. Are you sure if it's that? I really have no idea about working with RSS.

**Comment by webpro** [comment]
RSS is pretty common for people to read newsletters like yours.

https://lmgtfy.com/?q=what+is+rss

**Pull request merged**
