### PR TITLE
Expandable Lists

### PR DESCRIPTION
**Pull request by rouzbeh84**
Referenced in issue #3 from @tomByrer but not alphabetized yet as this seems to have cut down on the clutter mentioned considerable :)

### CODE REVIEW

**Comment by rouzbeh84** [comment]
If you do decide to merge this just let me know and I will update #4 accordingly. Also I think this gives some more flexibility as to what you can/can't include since they become paragraph/list format over table 👍

**Comment by webpro** [comment]
Thanks @rouzbeh84, I really like the idea. But I think expanding single items would be even better (so people can see all newsletters at a glance, and click one for details). What do you think?

**Comment by rouzbeh84** [comment]
Ah you mean like the newsletter titles that expand in to the details? 

```
## Front End

Newsletter Title (expand for details)

Newsletter Title (expand for details)

Newsletter Title (expand for details)
```
I like that idea as well. I can update and try to create a template for future PR's tomorrow.

**Comment by webpro** [comment]
Yes, exactly :-) I think you can leave out the "expand for details" text, since that's what happens automatically if you click it. Thanks for your contribution(s) in advance.

**Comment by rouzbeh84** [comment]
It's been updated but I didn't realize so much had been added... let me know what you'd like to do here as I won't be able to get to it until later

**Comment by rouzbeh84** [comment]
added the rest and resolved conflicts

**Comment by rouzbeh84** [comment]
ok, mixed up some branches but should be good to go now 👍

**Comment by webpro** [comment]
@rouzbeh84 I'm sorry for your efforts, but I've tried a different table layout and I'm kind of satisfied with it. Hope you like it, too? The expandable items looked neat, but having to click twice to go somewhere isn't very user-friendly.

**Comment by rouzbeh84** [comment]
sure, however you like it.

**Pull request closed without merging**
